"""Build the master timeline (scenes + narration cues) from script.json.

If synthesised narration clips exist (build/tts/manifest.json, written by
tts_kokoro.py), their *measured* durations drive every scene length and every
subtitle timestamp.  Otherwise durations are estimated from syllable counts so
the picture can be developed before the voice-over exists.

Outputs:
  build/timeline.json   - consumed by music/subtitle/mix tools
  web/timeline.js       - same data as an ES module for the renderer
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from textnorm import split_subtitle_segments, display_sub, syllables, tts_text, STRONG  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EST_RATE = 5.3          # syllables per second (estimate only)
GAP_WEAK = 0.12         # pause after a comma-type segment
GAP_STRONG = 0.30       # pause after a sentence end
GAP_LINE = 0.06         # extra pause between script lines
PAD_SCALE = 0.72        # scales each scene's pre/post padding from script.json
CHAPTER_LEAD = 0.0


def main():
    script = json.load(open(os.path.join(ROOT, "script", "script.json"), encoding="utf-8"))
    manifest_path = os.path.join(ROOT, "build", "tts", "manifest.json")
    measured = {}
    if os.path.exists(manifest_path):
        for item in json.load(open(manifest_path, encoding="utf-8"))["clips"]:
            measured[item["key"]] = item
    use_audio = bool(measured)

    t = 0.0
    scenes = []
    cues = []
    seg_index = 0
    chapter_start = {}
    for sc in script["scenes"]:
        start = t
        if sc["chapter"] not in chapter_start:
            chapter_start[sc["chapter"]] = start
        sc_cues = []
        if sc.get("fixed"):
            dur = sc["fixed"]
        else:
            cur = start + sc.get("pre", 0.4) * PAD_SCALE
            for li, line in enumerate(sc["lines"]):
                segs = split_subtitle_segments(line)
                for si, seg in enumerate(segs):
                    key = f"{seg_index:03d}"
                    if use_audio and key in measured:
                        d = measured[key]["dur"]
                    else:
                        d = syllables(seg) / EST_RATE + 0.15
                    cue = {
                        "key": key,
                        "scene": sc["id"],
                        "line": li,
                        "text": display_sub(seg),
                        "tts": tts_text(seg),
                        "start": round(cur, 3),
                        "end": round(cur + d, 3),
                    }
                    sc_cues.append(cue)
                    seg_index += 1
                    cur += d
                    last = seg.strip()[-1]
                    last = seg.strip().rstrip("”’》」』")[-1:] or last
                    cur += GAP_STRONG if last in STRONG else GAP_WEAK
                cur += GAP_LINE
            dur = (cur - start) + sc.get("post", 0.4) * PAD_SCALE
        dur = max(dur, sc.get("min", 0))
        scenes.append({
            "id": sc["id"],
            "chapter": sc["chapter"],
            "start": round(start, 3),
            "dur": round(dur, 3),
            "cues": [{"text": c["text"], "start": round(c["start"] - start, 3),
                      "end": round(c["end"] - start, 3), "line": c["line"]} for c in sc_cues],
        })
        cues.extend(sc_cues)
        t = start + dur

    total = round(t, 3)
    timeline = {
        "fps": 30,
        "width": 1920,
        "height": 1080,
        "total": total,
        "audio": "measured" if use_audio else "estimated",
        "chapters": [dict(c, start=round(chapter_start[c["id"]], 3)) for c in script["chapters"]],
        "scenes": scenes,
        "cues": cues,
    }
    if "--dry" in sys.argv:
        print(f"[dry] {len(scenes)} scenes, total {total:.2f}s ({timeline['audio']})")
        for c in timeline["chapters"]:
            print(f"  ch{c['id']} {c['title']} @ {c['start']:.1f}s")
        return
    os.makedirs(os.path.join(ROOT, "build"), exist_ok=True)
    json.dump(timeline, open(os.path.join(ROOT, "build", "timeline.json"), "w", encoding="utf-8"),
              ensure_ascii=False, indent=1)
    with open(os.path.join(ROOT, "web", "timeline.js"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/build_timeline.py - do not edit\n")
        f.write("export default ")
        json.dump({k: v for k, v in timeline.items() if k != "cues"}, f, ensure_ascii=False)
        f.write(";\n")
    print(f"timeline: {len(scenes)} scenes, {len(cues)} cues, total {total:.2f}s ({timeline['audio']})")
    for c in timeline["chapters"]:
        print(f"  ch{c['id']} {c['title']} @ {c['start']:.1f}s")


if __name__ == "__main__":
    main()
